repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
  - repo: 'https://github.com/psf/black'
    rev: 21.12b0
    hooks:
      - id: black
        args:
        - "--line-length=120"
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
        exclude: '^docs/[^/]*\.svg$'
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: file-contents-sorter
        files: |
          .gitignore
      - id: check-case-conflict
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-added-large-files
      - id: check-symlinks
      - id: debug-statements
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
        - "--max-line-length=120"
        - "--ignore=E203,W503"
        - "--select=W504"

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.ci hooks
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
