repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v0.0.4 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
  - repo: 'https://github.com/psf/black'
    rev: 21.6b0
    hooks:
      - id: black
        args:
        - "--line-length=120"
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: '^docs/[^/]*\.svg$'
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: file-contents-sorter
        files: |
          .gitignore
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-symlinks
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - '--allow-missing-credentials'
      - id: detect-private-key
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
        - "--max-line-length=120"
        - "--ignore=E203,W503"
        - "--select=W504"
